name: rollermusic
favicon: null
layout_spectrum: 0.89215
typography_spectrum: 0.27316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c0e0b'
    - '#b6c9d0'
    - '#929197'
    - '#f9f981'
    - '#684a48'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
